# Generated by Django 2.2.4 on 2019-08-26 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime_generated', models.DateTimeField()),
                ('energy_expected', models.DecimalField(decimal_places=14, max_digits=40)),
                ('energy_observed', models.DecimalField(decimal_places=14, max_digits=40)),
                ('irradiation_expected', models.DecimalField(decimal_places=14, max_digits=40)),
                ('irradiation_observed', models.DecimalField(decimal_places=14, max_digits=40)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Plant', verbose_name='plant_id')),
            ],
            options={
                'verbose_name': 'datapoint',
                'verbose_name_plural': 'datapoints',
            },
        ),
    ]
