# Generated by Django 2.2.4 on 2019-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190901_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
